export const subjects = {
  "8-9": ["Natural Sciences", "Mathematics", "Social Sciences"],
  "10-12": [
    "Mathematics", "Physical Sciences", "Business Studies", "English",
    "Agricultural Sciences", "Geography", "Life Sciences", "Mathematics Literacy", "Accounting"
  ]
};

export const dateFormat = { year: 'numeric', month: 'long', day: 'numeric' };

export const elements = {
  loginBtn: document.getElementById('loginBtn'),
  logoutBtn: document.getElementById('logoutBtn'),
  userInfo: document.getElementById('userInfo'),
  userAvatar: document.getElementById('userAvatar'),
  userName: document.getElementById('userName'),
  startApplicationBtn: document.getElementById('startApplicationBtn'),
  applicationSection: document.getElementById('applicationSection'),
  applicationForm: document.getElementById('applicationForm'),
  consentSection: document.getElementById('consentSection'),
  consentForm: document.getElementById('consentForm'),
  rulesSection: document.getElementById('rulesSection'),
  pledgeSection: document.getElementById('pledgeSection'),
  pledgeForm: document.getElementById('pledgeForm'),
  applicationStatus: document.getElementById('applicationStatus'),
  existingApplication: document.getElementById('existingApplication'),
  reportCardUpload: document.getElementById('reportCardUpload'),
  reportCard: document.getElementById('reportCard'),
  reportCardName: document.getElementById('reportCardName'),
  idDocumentUpload: document.getElementById('idDocumentUpload'),
  idDocument: document.getElementById('idDocument'),
  idDocumentName: document.getElementById('idDocumentName'),
  subjectsContainer: document.getElementById('subjectsContainer'),
  consentCheckbox: document.getElementById('parentConsent'),
  consentError: document.getElementById('parentConsentError'),
  rulesAgreement: document.getElementById('rulesAgreement'),
  rulesAgreementError: document.getElementById('rulesAgreementError'),
  finalAgreement: document.getElementById('finalAgreement'),
  finalAgreementError: document.getElementById('finalAgreementError'),
  gradeSelect: document.getElementById('grade'),
  emailInput: document.getElementById('email'),
  phoneInput: document.getElementById('phone'),
  parentEmailInput: document.getElementById('parentEmail'),
  parentPhoneInput: document.getElementById('parentPhone'),
  currentAppStatus: document.getElementById('currentAppStatus'),
  submittedDate: document.getElementById('submittedDate'),
  firstName: document.getElementById('firstName'),
  lastName: document.getElementById('lastName'),
  school: document.getElementById('school'),
  gender: document.getElementById('gender'),
  parentName: document.getElementById('parentName'),
  parentRelationship: document.getElementById('parentRelationship'),
  alternateContact: document.getElementById('alternateContact'),
  parentFullName: document.getElementById('parentFullName'),
  learnerFullName: document.getElementById('learnerFullName'),
  learnerId: document.getElementById('learnerId'),
  parentSignaturePad: document.getElementById('signaturePad'),
  clearSignature: document.getElementById('clearSignature'),
  parentSignature: document.getElementById('parentSignature'),
  parentConsentDate: document.getElementById('parentConsentDate'),
  learnerFullNamePledge: document.getElementById('learnerFullNamePledge'),
  learnerSignatureDate: document.getElementById('learnerSignatureDate'),
  learnerSignaturePad: document.getElementById('learnerSignaturePad'),
  clearLearnerSignature: document.getElementById('clearLearnerSignature'),
  learnerSignature: document.getElementById('learnerSignature'),
  parentFullNamePledge: document.getElementById('parentFullNamePledge'),
  parentSignatureDatePledge: document.getElementById('parentSignatureDatePledge'),
  parentSignaturePadPledge: document.getElementById('parentSignaturePadPledge'),
  clearParentSignaturePledge: document.getElementById('clearParentSignaturePledge'),
  parentSignaturePledge: document.getElementById('parentSignaturePledge'),
  nextToConsentBtn: document.getElementById('nextToConsentBtn'),
  backToApplicationBtn: document.getElementById('backToApplicationBtn'),
  nextToRulesBtn: document.getElementById('nextToRulesBtn'),
  backToConsentBtn: document.getElementById('backToConsentBtn'),
  nextToPledgeBtn: document.getElementById('nextToPledgeBtn'),
  backToRulesBtn: document.getElementById('backToRulesBtn'),
  contactSupportBtn: document.getElementById('contactSupportBtn'),
  toastContainer: document.getElementById('toastContainer'),
  currentYear: document.getElementById('currentYear')
};